name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook:
    git:
      url: https://github.com/mystster/widgetbook.git
      ref: fix_imcompatibility_freezed3
      path: packages/widgetbook
    
  widgetbook_annotation: ^3.3.1
  novel_seeker:
    path: ../
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.11.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
